CapsuleCorp/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('capsules.urls')),
    path('admin/', admin.site.urls),
]

capsules/urls.py
from django.urls import path
from . import views


app_name = 'capsulecoprs'
urlpatterns = [
    path('', views.index, name='index'),
    path('capsule/<str:id>', views.capsule, name='capsule'),
]

capsules/models.py
from django.db import models

#Model Capsule
class Capsule(models.Model):
    id = models.CharField(max_length=50, primary_key=True)
    reuse_count = models.IntegerField()
    water_landings = models.IntegerField()
    land_landings = models.IntegerField()
    last_update = models.CharField(max_length=255, blank=True, null=True)
    serial = models.CharField(max_length=50, blank=True, null=True)
    status = models.CharField(max_length=50, blank=True, null=True)
    type = models.CharField(max_length=50, blank=True, null=True)



    # Fonction pour deserialiser les données json en model Capsule
    def jsonToClass(self, aux):
        self.id = aux['id']
        self.reuse_count = aux['reuse_count']
        self.water_landings = aux['water_landings']
        self.land_landings = aux['land_landings']
        self.last_update = aux['last_update']
        self.serial = aux['serial']
        self.status = aux['status']
        self.type = aux['type']

capsules/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
import requests

from capsules.models import Capsule

#Vue - Lister capsules
def index(request):
    #Vérifie si la base de données SQLite contient déjà les données.
    #Si oui, affiche ces données
    data = Capsule.objects.all()
    if data.count:
        context = {
            'entries': data,
        }
        return render(request, 'index.html', context)

    #Sinon, lance une requête HTTP pour récupérer les données
    r = requests.get('https://api.spacexdata.com/v4/capsules')
    if r.status_code == 200:
        data = r.json()
        #Enregistre les données récupérées dans... 
        #la base de données avant de les affichées sur la page
        for x in data:
            capsule = Capsule()
            capsule.jsonToClass(x)
            capsule.save()
        context = {
            'entries': data,
        }
        return render(request, 'index.html', context)
    return HttpResponse('Could load save data, Please Retry')

#Vue - Voir details capsule
def capsule(request, id):
    capsule = Capsule.objects.get(id=id)
    template = loader.get_template('capsule.html')
    context = {
        'data': capsule,
    }
    return HttpResponse(template.render(context, request))

capsules/templates/capsule.html
<!-- Nous étendons le template principal-->
{% extends "dashboard.html" %}
{% block title %}Capsule Corp{% endblock %}

{% block content %}
{% load static %}
<div class="container">
  <div class="row mt-4">
    <!-- Section 1 (Card) : Images, serial, type, status, last update-->
    <div class="col-md-6 col-sm-12">
      <div class="card mr-auto overflow-hidden" style="max-width: 390px">
        <img src="{% static '/assets/capsule.jpg'%}" style="max-height: 250px;"/>
        <div style="margin-top: -70px; margin-left: 15px; display: flex; align-items: flex-end;">
          <div>
            <div class="card mr-auto" style="height:170px; width:130px; margin-right: 20px;">
              <img src="{% static '/assets/cap.png' %}" class="my-auto" />
            </div>
            <p class="mx-auto my-2" style="color: #7ec8e3;">{{ data.type }}</p>
          </div>
          <div style="padding-bottom: 40px">
            <h2 class="text-right">{{ data.serial }}</h2>
            <p class="mx-auto my-2 {{ data.status }} px-4 fw-semibold" style="border-radius: 5px;">{{ data.status }}</p>
          </div>
        </div>
        <p class="mx-auto my-1 mb-4 text-center">{{ data.last_update }}</p>
      </div>
    </div>

    <!-- Section 2 : reuse_count, land_water, land_landing -->
    <div class="col-md-6 col-sm-12 my-d-0 my-6 ">
      <div>
        <div class="d-flex align-items-center justify-content-between mb-4">
          <div class="d-flex align-items-center">
            <img src="{% static 'assets/recycle.png' %}" width="80px" height="80px" />
            <div class="mx-4 fs-3">Reuse</div>
          </div>
          <h2 class="mx-4" style="color: #000;">{% if data.reuse_count > 0 %}x{% endif %}{{data.reuse_count}}</div>
        </h2>
        <div class="d-flex align-items-center justify-content-between my-4">
          <div class="d-flex align-items-center">
            <img src="{% static 'assets/wave.png' %}" width="80px" height="80px" />
            <div class="mx-4 fs-3">Water landings</div>
          </div>
          <h2 class="mx-4" style="color: #000;">{% if data.water_landings > 0 %}x{% endif %}{{data.water_landings}}
          </h2>
        </div>
        <div class="d-flex align-items-center justify-content-between my-4">
          <div class="d-flex align-items-center">
            <img src="{% static 'assets/land.png' %}" width="80px" height="80px" />
            <div class="mx-4 fs-3">Land landings</div>
          </div>
          <h2 class="mx-4" style="color: #000; font-weight: 900;">{% if data.land_landings > 0 %}x{% endif %}{{data.land_landings}}
          </h2>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

capsules/templates/dashboard.html
<!-- Template principale -->
<!DOCTYPE html>
<html lang="fr">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  {% load static %}

  <link rel="apple-touch-icon" sizes="76x76" href="{% static 'assets/img/apple-icon.png' %}">
  <link rel="icon" type="image/png" href="{% static 'assets/img/favicon.png' %}">
  <title>
    {% block title %}
    Capsule Corp
    {% endblock %}
  </title>

  <!--     Fonts and icons     -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet" />
  <!-- Nucleo Icons -->
  <link href="{% static 'assets/css/nucleo-icons.css' %}" rel="stylesheet" />
  <link href="{% static 'assets/css/nucleo-svg.css' %}" rel="stylesheet" />
  <!-- Font Awesome Icons -->
  <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
  <link href="{% static 'assets/css/nucleo-svg.css' %}" rel="stylesheet" />
  <!-- CSS Files -->
  <link id="pagestyle" href="{% static 'assets/css/soft-ui-dashboard.css' %}" rel="stylesheet" />

  <!-- Style de couleur pour les diferent status -->
  <style>
    .active {
      color: #00FF55;
      background: #00FF5519;

    }

    .retired {
      color: #ff9f1c;
      background: #ff9f1c19;
    }

    .unknown {
      color: #000c66;
      background: #000c6619;
    }

    .removed {
      color: #f51720;
      background: #f5172019;
    }
  </style>
</head>

<body class="g-sidenav-show  bg-gray-100">
  <!-- Début section sidebar -->
  {% block sidebar %}
  <aside class="sidenav navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-3 "
    id="sidenav-main">
    <div class="sidenav-header">
      <i class="fas fa-times p-3 cursor-pointer text-secondary opacity-5 position-absolute end-0 top-0 d-none d-xl-none"
        aria-hidden="true" id="iconSidenav"></i>
      <a class="navbar-brand m-0" href="/">
        <img src="{% static 'assets/capsulecorps.png' %}" class="navbar-brand-img h-100" alt="main_logo">
        <span class="ms-1 font-weight-bold">Capsule Corp</span>
      </a>
    </div>
    <hr class="horizontal dark mt-0">
    <div class="collapse navbar-collapse  w-auto  max-height-vh-100 h-100" id="sidenav-collapse-main">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link  active" href="{% url 'capsulecoprs:index' %}">
            <div
              class="icon icon-shape icon-sm shadow border-radius-md bg-white text-center me-2 d-flex align-items-center justify-content-center">
              <svg width="12px" height="12px" viewBox="0 0 45 40" version="1.1" xmlns="http://www.w3.org/2000/svg"
                xmlns:xlink="http://www.w3.org/1999/xlink">
                <title>shop </title>
                <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                  <g transform="translate(-1716.000000, -439.000000)" fill="#FFFFFF" fill-rule="nonzero">
                    <g transform="translate(1716.000000, 291.000000)">
                      <g transform="translate(0.000000, 148.000000)">
                        <path class="color-background opacity-6"
                          d="M46.7199583,10.7414583 L40.8449583,0.949791667 C40.4909749,0.360605034 39.8540131,0 39.1666667,0 L7.83333333,0 C7.1459869,0 6.50902508,0.360605034 6.15504167,0.949791667 L0.280041667,10.7414583 C0.0969176761,11.0460037 -1.23209662e-05,11.3946378 -1.23209662e-05,11.75 C-0.00758042603,16.0663731 3.48367543,19.5725301 7.80004167,19.5833333 L7.81570833,19.5833333 C9.75003686,19.5882688 11.6168794,18.8726691 13.0522917,17.5760417 C16.0171492,20.2556967 20.5292675,20.2556967 23.494125,17.5760417 C26.4604562,20.2616016 30.9794188,20.2616016 33.94575,17.5760417 C36.2421905,19.6477597 39.5441143,20.1708521 42.3684437,18.9103691 C45.1927731,17.649886 47.0084685,14.8428276 47.0000295,11.75 C47.0000295,11.3946378 46.9030823,11.0460037 46.7199583,10.7414583 Z">
                        </path>
                        <path class="color-background"
                          d="M39.198,22.4912623 C37.3776246,22.4928106 35.5817531,22.0149171 33.951625,21.0951667 L33.92225,21.1107282 C31.1430221,22.6838032 27.9255001,22.9318916 24.9844167,21.7998837 C24.4750389,21.605469 23.9777983,21.3722567 23.4960833,21.1018359 L23.4745417,21.1129513 C20.6961809,22.6871153 17.4786145,22.9344611 14.5386667,21.7998837 C14.029926,21.6054643 13.533337,21.3722507 13.0522917,21.1018359 C11.4250962,22.0190609 9.63246555,22.4947009 7.81570833,22.4912623 C7.16510551,22.4842162 6.51607673,22.4173045 5.875,22.2911849 L5.875,44.7220845 C5.875,45.9498589 6.7517757,46.9451667 7.83333333,46.9451667 L19.5833333,46.9451667 L19.5833333,33.6066734 L27.4166667,33.6066734 L27.4166667,46.9451667 L39.1666667,46.9451667 C40.2482243,46.9451667 41.125,45.9498589 41.125,44.7220845 L41.125,22.2822926 C40.4887822,22.4116582 39.8442868,22.4815492 39.198,22.4912623 Z">
                        </path>
                      </g>
                    </g>
                  </g>
                </g>
              </svg>
            </div>
            <span class="nav-link-text ms-1">Liste des Capsules</span>
          </a>
        </li>
      </ul>
    </div>
    <div class="sidenav-footer mx-3 ">

    </div>
  </aside>
  {% endblock %}
  <!-- Fin section sidebar -->

  <main class="main-content position-relative max-height-vh-100 h-100 mt-1 border-radius-lg ">
    <!-- Navbar -->
    {% block navbar %}
    <nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl" id="navbarBlur"
      navbar-scroll="true">
      <div class="container-fluid py-1 px-3">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb bg-transparent mb-0 pb-0 pt-1 px-0 me-sm-6 me-5">
            <li class="breadcrumb-item text-sm"><a class="opacity-5 text-dark" href="javascript:;">Pages</a></li>
            <li class="breadcrumb-item text-sm text-dark active" aria-current="page">Capsules</li>
          </ol>
          <h6 class="font-weight-bolder mb-0">Capsules Corp</h6>
        </nav>
        <div class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4" id="navbar">
          <div class="ms-md-auto pe-md-3 d-flex align-items-center">
            <div class="input-group">
              <span class="input-group-text text-body"><i class="fas fa-search" aria-hidden="true"></i></span>
              <input type="text" class="form-control" placeholder="Rechercher...">
            </div>
          </div>
          <ul class="navbar-nav  justify-content-end">
            <li class="nav-item d-xl-none ps-3 d-flex align-items-center">
              <a href="javascript:;" class="nav-link text-body p-0" id="iconNavbarSidenav">
                <div class="sidenav-toggler-inner">
                  <i class="sidenav-toggler-line"></i>
                  <i class="sidenav-toggler-line"></i>
                  <i class="sidenav-toggler-line"></i>
                </div>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    {% endblock %}
    <!-- End Navbar -->

    <div class="container-fluid py-4">
      <!-- bloc content -->
      {% block content %}{% endblock %}
    </div>
  </main>
  <div class="fixed-plugin">
    <div class="card shadow-lg ">
      <div class="card-body pt-sm-3 pt-0">
        <div class="form-check form-switch ps-0">
          <input class="form-check-input mt-1 ms-auto" type="checkbox" id="navbarFixed" onclick="navbarFixed(this)">
        </div>
      </div>
    </div>
  </div>
  <!--   Core JS Files   -->
  <script src="{% static 'assets/js/core/popper.min.js' %}"></script>
  <script src="{% static 'assets/js/core/bootstrap.min.js' %}"></script>
  <script src="{% static 'assets/js/plugins/perfect-scrollbar.min.js' %}"></script>
  <script src="{% static 'assets/js/plugins/smooth-scrollbar.min.js' %}"></script>

  <script>
    var win = navigator.platform.indexOf('Win') > -1;
    if (win && document.querySelector('#sidenav-scrollbar')) {
      var options = {
        damping: '0.5'
      }
      Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
    }
  </script>
  <!-- Github buttons -->
  <script async defer src="https://buttons.github.io/buttons.js"></script>
  <!-- Control Center for Soft Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="{% static 'assets/js/soft-ui-dashboard.min.js' %}"></script>
</body>

</html>

capsules/templates/index.html
<!-- Nous étendons le template principal-->
{% extends "dashboard.html" %}
{% block title %}Capsule Corp{% endblock %}

{% block content %}
{% load static %}
<div class="row">
  <div class="col-12">
    <div class="card mb-4">
      <div class="card-header pb-0 d-flex align-items-center justify-content-between">
        <h6>Liste des Capsules</h6>
      </div>
      <div class="card-body px-0 pt-0 pb-2">
        <div class="table-responsive p-0">
          <table class="table align-items-center justify-content-center mb-0">
            <thead>
              <tr>
                <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Numéro de Série</th>
                <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Type</th>
                <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Statut</th>
                <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2"></th>
              </tr>
            </thead>
            <tbody>
              <!-- Contenue principal - Inflation du tableau par les donnés envoyés par la 'view' -->
              {% for entry in entries %}
              <tr>
                  <td>
                    <div class="d-flex px-2">
                      
                      <div class="my-auto">
                        <h6 class="mb-0 text-sm">{{ entry.serial}}</h6>
                      </div>
                    </div>
                  </td>
                  <td>
                    <p class="text-sm font-weight-bold mb-0">
                      {{  entry.type }}
                    </p>
                  </td>
                  <td>
                    <p class="text-sm font-weight-bold mb-0">
                      {{  entry.status }}
                    </p>
                  </td>
                  <td class="align-middle">
                    <div class="dropdown">
                      <a href="capsule/{{ entry.id }}"  class="btn btn-link" >Voir plus</a>
                    </div>
                  </td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}